language: python
python: "3.6"

cache:
  directories:
    - cabi/target
    - py/venv
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target
  timeout: 1200

git:
  depth: 1

env:
  global:
    - IMAGE_NAME=getsentry/semaphore
    # DOCKER_USER
    - secure: "G2yD0snSwzlzxOzUXBVJcwo0nGVuTTndaGM+yQKkVGXq/S2OR2xwgyc81GW2u6qky/ISAcaqwE7+MlG7qaAOx2mQawpHgT9J9+teMcjiGIhcg0YFm4ef4Ry55kNbMsPC/FzWcx2qFo9Gfk0WQasM1stjz6Eet/6Zm7RLHLBwzxz+aFCrXwbYqkgyV76AUISuZZDvl325oRmZzi1S7Z/uty/nrAoDSH3qSh1LftTVj9g1kKzirTcDV66aXz3hYK+FmnaWfmin/Z7DWA5+r80M87kFhXE6iOeXx0JEmHb73RwHYzLFzfhQNBFoLtVe01DuNwDtzri/JqAXgLmSCrUZFfkVRZgiBQptOPNqD8lT2JWYVX5pTB1PSpp+GOccizfkQ7JTnVT4CNaNHs00CXEcAkd/jnq6BVYVG26pKwTq6dTp7dzT4wSBfl7VXPXSGAwXkbcNp+15sfNNKkoTwdiLmtPjzGXttAqHMARp832Aj3YxIwD4ar1h2F7W+Hu4WQK1WD1qf6yl0T0mqBnH2xnbgKzp1akEQhGOvCoH6ySEUPPoQ5M6enZTetcV5EdtQrXrBwMun+O5IyxTzpYegKv8n1aRlNysqapYD3Z/e58OwepnGKsOv08Ru9oO8/BqgcyDipsj4BO8s0iOU6b3KcSJp6eFNdNszme6JftTzV3jItM="
    # DOCKER_PASS
    - secure: "cn8IG8G8wELnompspaFZ0xqeuLmGr4fuyMRBz6PG9hBay8uQhsd/+xQijLq0+ZL3bG9q9F7ceHUFlTgiWwERly+CXhO0miPGj+rbPvH3X+5L0UJNjV3qScCePn0IvxQiXg4WtO3Zy9kcoPQqedsh0gAvO1vQILEbX8HH03uq8jddni4FPw2RruTNnWukG6oPlUxCdnrRFh9l542mciUqzZOs2eHvETl32hH+b+0Lx3SJF1rjxd2SsSMCg4/7yXLfqaBOBQfG5OW8OSgqS34Fdht4CMyhbEx9mSMsWFDxP2FHVGI0KIFZvpIuouh9aUI0imEJzy6Mk2xR13Z3/1SQunOMCQHnMmMN4nhG51U8HxbJRykV/LgfksVD0T7tquVZB9SJ7y6upBtkbqXkk0K4OOuE1QBnBPvOUvujsEBRHoPlZRFGSKTGKEKwZRILmTUz0VUqvIUFL2eAHYJNNS+WB+T+xjZ3alInKVNCAfhnNhyODWX0QkZHmMhzCTPCM4+ujrfeemN8oJty7mZxFRv86bU+PQofdB7bjpYtI8hHKtP9vEGYWdgIT2cBpNNTaxxvy/sLB1ERVi7KCRj6P+ird+3JNcN0e7ZVFnJwZ+2T5dkb0WvbA0l6QuMjVy9vlWnS+fTIbeT+hGIdq/U9fN9Jpb2GGxL1ofXNZ07SJCjIkD0="

branches:
  only:
    - master
    - /^release\/[\d.]+$/

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_TOOLCHAIN:-stable}
  - export PATH=~/.cargo/bin/:$PATH

install: skip

before_cache:
  - make clean-target-dir

matrix:
  fast_finish: true
  include:
    # -------------------------------------
    # STATIC ANALYSIS
    # -------------------------------------

    - name: "check: codestyle"
      script: make -e format-check

    - name: "check: lint"
      script: make -e lint

    # -------------------------------------
    # RUST TESTS
    # -------------------------------------

    - name: "test: semaphore[linux]"
      os: linux
      env: RUST_TOOLCHAIN=nightly-2019-01-09
      sudo: required
      addons:
        apt:
          packages:
            - libssl-dev
            - libgeoip-dev
      install:
        - cargo tarpaulin --version || RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force cargo-tarpaulin --git https://github.com/untitaker/tarpaulin --branch fix/upgrade-cargo
      script:
        - make -e cargotest-cov

    - name: "test: semaphore[macos]"
      os: osx
      language: generic
      install: cargo build --all
      script: make -e cargotest

    # -------------------------------------
    # PYTHON LIBRARY TESTS
    # -------------------------------------

    - name: "test: libsemaphore"
      os: linux
      script: make -e pytest

    # -------------------------------------
    # EXECUTALE INTEGRATION TESTS
    # -------------------------------------

    - name: "integration-test: semaphore"
      os: linux
      # https://github.com/travis-ci/travis-ci/issues/9831
      sudo: true
      install:
        - export PATH=$PATH:$HOME/.cargo/bin
        - wget https://github.com/yyyar/gobetween/releases/download/0.6.0/gobetween_0.6.0_linux_amd64.tar.gz -O - | tar xz; mv gobetween $HOME/.cargo/bin
        - sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
        - sudo apt-get update
        - sudo apt-get install haproxy -y
      script:
        - make -e integration-test

    # -------------------------------------
    # RUST RELEASE BUILDS
    # -------------------------------------

    - name: "release: semaphore[linux]"
      os: linux
      language: generic
      services:
        - docker
      env:
        - BUILD_ARCH=x86_64
      script:
        - make -e releasebuild-docker
        - npm install -g @zeus-ci/cli || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]
        - zeus upload -t "application/octet-stream" -n semaphore-Linux-x86_64 target/x86_64-unknown-linux-gnu/release/semaphore  || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]
        - zip semaphore-debug.zip target/x86_64-unknown-linux-gnu/release/semaphore.debug
        - zeus upload -t "application/octet-stream" -n semaphore-Linux-x86_64-debug.zip semaphore-debug.zip  || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]
        # Build and push image to Dockerhub, on master branch only
        - bash scripts/push-docker-image.sh

    # - os: linux
    #   language: generic
    #   env:
    #     - BUILD_ARCH=i686
    #   script:
    #     - make -e releasebuild-docker
    #     - npm install -g @zeus-ci/cli
    #     - zeus upload -t "application/octet-stream"
    #                   -n semaphore-Linux-i686
    #                   target/i686-unknown-linux-gnu/release/semaphore

    - name: "release: semaphore[macos]"
      os: osx
      language: generic
      script:
        - make -e releasebuild
        - npm install -g @zeus-ci/cli || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]
        - zeus upload -t "application/octet-stream" -n semaphore-Darwin-x86_64 target/release/semaphore || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]
        - zip -r semaphore-dsym.zip target/release/semaphore.dSYM
        - zeus upload -t "application/octet-stream" -n semaphore-Darwin-x86_64-dsym.zip semaphore-dsym.zip || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]

    # -------------------------------------
    # PYTHON RELEASE BUILDS
    # -------------------------------------

    - name: "release: libsemaphore[linux-x86]"
      os: linux
      sudo: required
      env: BUILD_ARCH=i686
      language: generic
      script:
        - make -e manylinux
        - npm install -g @zeus-ci/cli || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]
        - zeus upload -t "application/zip+wheel" py/dist/* || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]

    - name: "release: libsemaphore[linux-x86_64]"
      sudo: required
      env: BUILD_ARCH=x86_64
      language: generic
      script:
        - make -e manylinux
        - npm install -g @zeus-ci/cli || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]
        - zeus upload -t "application/zip+wheel" py/dist/* || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]

    - name: "release: libsemaphore[macos]"
      os: osx
      language: generic
      osx_image: xcode7.3
      env: SEMAPHORE_PYTHON_VERSION=python
      script:
        - make -e wheel
        - npm install -g @zeus-ci/cli || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]
        - zeus upload -t "application/zip+wheel" py/dist/* || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]

    - name: "release: libsemaphore[sdist]"
      os: linux
      sudo: required
      language: generic
      script:
        - make -e sdist
        - npm install -g @zeus-ci/cli || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]
        - zeus upload -t "application/zip+wheel" py/dist/* || [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/a3901574-fbb7-11e7-9451-0a580a280114/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
