os: linux
language: rust
cache:
  cargo: true

git:
  depth: 1

branches:
  only:
    - master

before_script:
  - sudo apt-get install libgeoip-dev

script: make $SUITE

matrix:
  include:
    - env: SUITE=format-check
    - env: SUITE=lint
    - env: SUITE=test
