language: rust
cache: cargo

git:
  depth: 1

if: tag IS blank
install: cargo build --all
script: .ci/suite.sh

matrix:
  include:
    - os: linux
      sudo: required
      env: SUITE=test
    - os: osx
      env: SUITE=test
    - os: linux
      env: SUITE=format
      install: cargo install rustfmt-preview

before_install:
  - .ci/install-libsodium.sh

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/a3901574-fbb7-11e7-9451-0a580a280114/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
