language: rust
cache: cargo

git:
  depth: 1

os:
  - linux
  - osx

if: tag IS blank
install: cargo build --all
script: cargo test --all

matrix:
  include:
    os: linux
    rust: nightly
    install: cargo install rustfmt-nightly --force
    script: cargo fmt -- --write-mode diff

before_install:
  - .ci/install-libsodium.sh

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/a3901574-fbb7-11e7-9451-0a580a280114/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
