language: rust
cache: cargo

git:
  depth: 1

if: tag IS blank

matrix:
  include:
    - os: linux
      sudo: required
      env: SUITE=test
      before_install: .ci/install-libsodium.sh
      install: cargo build --all
      script: cargo test --all
    - os: osx
      env: SUITE=test
      before_install: .ci/install-libsodium.sh
      install: cargo build --all
      script: cargo test --all
    - os: linux
      env: SUITE=format
      install: rustup component add rustfmt-preview
      script: cargo fmt -- --write-mode diff

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/a3901574-fbb7-11e7-9451-0a580a280114/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
