[package]
name = "sentry-agent"
version = "0.1.0"
license = "MIT"
authors = ["Sentry <hello@sentry.io>"]
readme = "README.md"
description = """
An proxy service for Sentry.
"""
exclude = [
    ".vscode/**/*",
]

[workspace]

[dependencies]
smith-common = { version = "0.1.0", path = "common" }
smith-server = { version = "0.1.0", path = "server" }
