[package]
name = "general"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
debugid = { version = "0.3.1", features = ["with_serde"] }
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
uuid = { version = "0.7.1", features = ["v4", "serde"] }
general_derive = { path = "derive" }
smallvec = { version = "0.6.5", features = ["serde"] }
failure = "0.1.3"
failure_derive = "0.1.3"
chrono = "0.4.6"
cookie = { version = "0.11.0", features = ["percent-encode"] }
url = "1.7.1"
itertools = "0.7.8"

[patch.crates-io]
synstructure = { git = "https://github.com/mitsuhiko/synstructure", rev = "d5e1bb3c00a24a001568e88be6a94d0613049bda" }

[dev-dependencies]
difference = "2.0.0"
