[package]
name = "general"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
uuid = { version = "0.7.1", features = ["v4", "serde"] }
general_derive = { path = "derive" }
smallvec = { version = "0.6.5", features = ["serde"] }
