[package]
authors = ["Sentry <hello@sentry.io>"]
description = "An proxy service for Sentry.\n"
exclude = [".vscode/**/*"]
license = "MIT"
name = "sentry-agent"
readme = "README.md"
version = "0.1.0"

[dependencies]
failure = "0.1.1"

[dependencies.smith-common]
path = "common"
version = "0.1.0"

[dependencies.smith-server]
path = "server"
version = "0.1.0"

[workspace]
