[package]
name = "semaphore-general"
version = "0.2.4"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
chrono = "0.4.6"
cookie = { version = "0.11.0", features = ["percent-encode"] }
debugid = { version = "0.3.1", features = ["with_serde"] }
failure = "0.1.3"
failure_derive = "0.1.3"
semaphore-general-derive = { path = "derive" }
itertools = "0.7.11"
lazy_static = "1.2.0"
maxminddb = "0.11.0"
regex = "1.1.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
serde_urlencoded = "0.5.4"
smallvec = { version = "0.6.7", features = ["serde"] }
url = "1.7.2"
uuid = { version = "0.7.1", features = ["v4", "serde"] }
num-traits = "0.2.6"
sha2 = "0.8.0"
hmac = "0.7.0"
sha-1 = "0.8.1"

[dev-dependencies]
difference = "2.0.0"

[features]
bench = []
