[package]
authors = ["Sentry <hello@sentry.io>"]
description = "A helper library for managing different aortas"
documentation = "https://docs.rs/semaphore-trove"
homepage = "https://github.com/getsentry/semaphore"
license = "MIT"
name = "semaphore-trove"
repository = "https://github.com/getsentry/semaphore"
version = "0.1.3"

[dependencies]
failure = "0.1.2"
failure_derive = "0.1.2"
futures = "0.1.23"
log = "0.4.3"
parking_lot = "0.6.3"
tokio-core = "0.1.17"
hyper = "0.11.27"
hyper-tls = "0.1.3"
native-tls = "0.2.0"
serde_json = "1.0.24"
serde = "1.0.70"
serde_derive = "1.0.70"

[dependencies.semaphore-aorta]
path = "../aorta"

[dependencies.semaphore-common]
path = "../common"
