[package]
authors = ["Sentry <hello@sentry.io>"]
description = "The agent <-> backend communcation and authentication protocol"
documentation = "https://docs.rs/smith-common"
homepage = "https://github.com/getsentry/sentry-agent"
license = "MIT"
name = "smith-aorta"
repository = "https://github.com/getsentry/sentry-agent"
version = "0.1.0"

[dependencies]
base64 = "0.9.0"
failure = "0.1.1"
failure_derive = "0.1.1"
serde = "1.0.27"
serde_json = "1.0.9"
sodiumoxide = "0.0.16"

[dependencies.uuid]
features = ["v4", "serde"]
version = "0.5.1"
