[package]
authors = ["Sentry <hello@sentry.io>"]
description = "Server components for the agent"
documentation = "https://docs.rs/smith-server"
homepage = "https://github.com/getsentry/sentry-agent"
license = "MIT"
name = "smith-server"
repository = "https://github.com/getsentry/sentry-agent"
version = "0.1.0"

[dependencies]
clap = "2.29.2"
failure = "0.1.1"
failure_derive = "0.1.1"
hyper = "0.11.14"
