[package]
name = "smith-cabi"
version = "0.1.0"
license = "MIT"
authors = ["Sentry <hello@sentry.io>"]
homepage = "https://github.com/getsentry/sentry-relay"
repository = "https://github.com/getsentry/sentry-relay"
description = "Exposes some internals of the agent to C."

[lib]
name = "smith"
crate-type = ["cdylib"]

[workspace]

[profile.release]
debug = true

[dependencies]
smith-aorta = { version = "0.1.0", path = "../aorta" }
failure = "0.1.1"
uuid = "0.6.0"
serde_json = "1.0.9"
chrono = "0.4.0"
serde_derive = "1.0.27"
serde = "1.0.27"
