[package]
name = "semaphore-cabi"
version = "0.1.3"
license = "MIT"
authors = ["Sentry <hello@sentry.io>"]
homepage = "https://github.com/getsentry/semaphore"
repository = "https://github.com/getsentry/semaphore"
description = "Exposes some internals of the relay to C."

[lib]
name = "semaphore"
crate-type = ["cdylib"]

[workspace]

[profile.release]
debug = true
lto = true

[dependencies]
failure = "0.1.1"
uuid = "0.6.3"
serde_json = "1.0.17"
chrono = "0.4.2"
serde_derive = "1.0.45"
serde = "1.0.45"

[dependencies.semaphore-aorta]
path = "../aorta"

[patch.crates-io]
sentry = { git = "https://github.com/getsentry/sentry-rust", rev = "0bf9723d4bbb1820033d4d6906407c0df0d59286" }
sentry-types = { git = "https://github.com/getsentry/rust-sentry-types", rev = "3bb7f3847480676d753288b137e8f95a4f3af020" }
serde = { git = "https://github.com/mitsuhiko/serde", rev = "880a8c0181ad7202950f24cc8f6872994913441d" }
serde_derive = { git = "https://github.com/mitsuhiko/serde", rev = "880a8c0181ad7202950f24cc8f6872994913441d" }
