[package]
authors = ["Sentry <hello@sentry.io>"]
description = "Common functionality for the sentry relay"
documentation = "https://docs.rs/smith-common"
homepage = "https://github.com/getsentry/sentry-relay"
license = "MIT"
name = "smith-common"
repository = "https://github.com/getsentry/sentry-relay"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
url = "1.7.0"
serde = "1.0.43"
serde_derive = "1.0.43"
serde_json = "1.0.16"
hyper = "0.11.25"
sentry-types = "0.3.2"
lazy_static = "1.0.0"
cadence = "0.14.0"
parking_lot = "0.5.5"
log = "0.4.1"
